---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
## Loading required package: viridisLite
library(p8105.datasets)

library(plotly)

data(nyc_airbnb)

data("nyc_airbnb")

data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  rename(latitude = lat, longitude = long) %>%
  select(
    boro = neighbourhood_group, neighbourhood, rating, price, room_type,
    latitude, longitude) %>%
  filter(!is.na(rating))
``` 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
boros = nyc_airbnb %>% distinct(boro) %>% pull()

# selectInput widget
selectInput(
  "boro_choice", 
  label = h3("Select borough"),
  choices = boros, selected = "Manhattan")


sliderInput(
  inputId = "price_range",
  label = h3("Price Range"),
  min=50, max=1000, value=c(100,250)
)

room_choice = nyc_airbnb %>% distinct(room_type) %>% pull()

radioButtons(
  inputId = "room_choice",
  label = h3("Room Type"),
  choices = room_choice,
  selected = "Entire home/apt"
)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
nyc_airbnb %>% 
  filter(boro == input[["boro_choice"]],
         price >= input[["price_range"]][1],
         price <= input[["price_range"]][2],
         room_type == input$room_choice) %>% 
  plot_ly(x=~latitude,y=~longitude, color = ~price,
          type = "scatter",mode="markers",alpha=.5)
})


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPrint({ 
  input[["price_range"]]
})
```

### Chart C

```{r}
renderPrint({ 
  input[["room_choice"]]
})
```